---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# limix

## Setup 
```r
pak::pak("frankiethull/limix")

limix::create_limix_env()
limix::use_limix_env()
limix::install_limix_dependencies()
```

## Example

```{r example}
library(limix)
library(rsample)
limix::use_limix_env()

corn_data <- maize::corn_data

corn_splits <- initial_validation_split(corn_data)
train <- training(corn_splits)
validate <- validation(corn_splits)
test <- testing(corn_splits)
```


### Classification
```{r}
# LimiX fit interface defaults to 16M and classifier configuration:
fit_cls <- limix_fit(
  train |> dplyr::select(-type),
  train$type,
  device = "cpu"
)

class_preds <- limix_predict(fit_cls, test |> dplyr::select(-type))

# LimiX supports proba and only proba by default:
class_preds |> head()
```

### Regression
```{r}
# setting to a different config
fit_reg <- limix_fit(
  train |> dplyr::select(-height),
  train$height,
  device = "cpu",
  limix_model = "2M",
  limix_config = "reg_default_noretrieval"
)

predictions <- limix_predict(
  fit_reg,
  test |> dplyr::select(-height),
  task_type = "Regression"
)

predictions |> head()
```
